/**
 * Extended Customer Dataset
 *
 * 24 complete customer profiles with purchase histories, channel attribution,
 * lifecycle stages, propensity scores, and journey context.
 *
 * Consistent with segments and archetypes shown in app/customers/page.tsx.
 * SKU naming: [3-letter category]-[3-digit number]
 */

export type CustomerSegment = "High Value" | "Growth" | "At Risk" | "Dormant";
export type CustomerArchetype =
  | "Loyal Buyer"
  | "Brand Advocate"
  | "Deal Hunter"
  | "Trend Follower"
  | "Occasional Buyer"
  | "Bargain Seeker";
export type ChurnRisk = "Low" | "Medium" | "High";
export type TrendDirection = "up" | "down" | "flat";

export interface PurchaseEvent {
  date: string;          // e.g. "12 Mar 2026"
  sku: string;
  product: string;
  channel: "Email" | "Direct" | "Search" | "Social" | "Affiliate";
  spend: number;         // £
  returnedOn?: string;   // date if returned
}

export interface CustomerProfile {
  id: number;
  name: string;
  email: string;
  city: string;
  age: number;
  segment: CustomerSegment;
  archetype: CustomerArchetype;
  ltv: number;                   // lifetime value £
  acquisitionChannel: string;
  acquisitionDate: string;       // "Jan 2024"
  lastPurchase: string;          // relative "3 days ago"
  purchaseCount: number;
  avgOrderValue: number;         // £
  purchaseHistory: PurchaseEvent[];
  preferredChannel: string;
  emailOpenRate: number;         // %
  engagementScore: number;       // 0-100
  propensityToChurn: ChurnRisk;
  nextBestAction: string;
  trend: TrendDirection;
  riskScore: ChurnRisk;
  tags: string[];
}

// ── Extended product catalogue (SKUs used across purchase histories) ─────────

export const PRODUCT_CATALOGUE: Record<string, { name: string; category: string; price: number }> = {
  "UWJ-244": { name: "Urban Winter Jacket", category: "Outerwear", price: 85 },
  "PRS-819": { name: "Performance Running Shoes", category: "Footwear", price: 79 },
  "SFT-102": { name: "Smart Fitness Tracker", category: "Fitness Electronics", price: 91 },
  "TPB-551": { name: "Travel Pro Backpack", category: "Bags & Luggage", price: 86 },
  "EHD-331": { name: "Essential Hoodie", category: "Basics & Essentials", price: 56 },
  "CWL-119": { name: "Cashmere Wool Layer", category: "Outerwear", price: 89 },
  "AWJ-302": { name: "Active Windbreaker", category: "Outerwear", price: 65 },
  "YGS-224": { name: "Yoga Studio Shorts", category: "Activewear", price: 38 },
  "PRG-445": { name: "Pro Running Gloves", category: "Activewear", price: 24 },
  "SWT-887": { name: "Insulated Sports Bottle", category: "Accessories", price: 22 },
  "OMB-234": { name: "Oxford Messenger Bag", category: "Bags & Luggage", price: 95 },
  "LGG-778": { name: "Lightweight Gym Gloves", category: "Activewear", price: 28 },
  "WBL-156": { name: "Waterproof Base Layer", category: "Outerwear", price: 74 },
  "CTN-421": { name: "Classic Cotton Tee", category: "Basics & Essentials", price: 29 },
  "DSC-091": { name: "Dual-Speed Cycling Kit", category: "Activewear", price: 112 },
  "RBS-662": { name: "Ribbed Running Socks 3-Pack", category: "Accessories", price: 18 },
  "TRL-445": { name: "Trail Running Leggings", category: "Activewear", price: 62 },
  "SCF-203": { name: "Merino Scarf & Glove Set", category: "Accessories", price: 44 },
  "FNP-318": { name: "Foldable Neoprene Tote", category: "Bags & Luggage", price: 42 },
  "XTR-509": { name: "Extreme Cold Thermal Vest", category: "Outerwear", price: 58 },
};

// ── 24 customer profiles ─────────────────────────────────────────────────────

export const CUSTOMERS: CustomerProfile[] = [
  // ── HIGH VALUE ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Emma Lindqvist",
    email: "emma.l@email.com",
    city: "London",
    age: 34,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 48200,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Sep 2021",
    lastPurchase: "2 days ago",
    purchaseCount: 47,
    avgOrderValue: 102,
    purchaseHistory: [
      { date: "13 Mar 2026", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
      { date: "21 Feb 2026", sku: "UWJ-244", product: "Urban Winter Jacket", channel: "Direct", spend: 85 },
      { date: "04 Feb 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Direct", spend: 38 },
      { date: "18 Jan 2026", sku: "SFT-102", product: "Smart Fitness Tracker", channel: "Email", spend: 91 },
      { date: "02 Dec 2025", sku: "EHD-331", product: "Essential Hoodie", channel: "Direct", spend: 56 },
      { date: "14 Nov 2025", sku: "TPB-551", product: "Travel Pro Backpack", channel: "Email", spend: 86 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 68,
    engagementScore: 91,
    propensityToChurn: "Low",
    nextBestAction: "Upsell to Cashmere premium range — high affinity for outerwear",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "email-engaged", "outerwear-affinity"],
  },
  {
    id: 2,
    name: "Marcus Bergström",
    email: "m.bergstrom@email.com",
    city: "Manchester",
    age: 29,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 12400,
    acquisitionChannel: "TikTok Ad",
    acquisitionDate: "Mar 2023",
    lastPurchase: "45 days ago",
    purchaseCount: 18,
    avgOrderValue: 69,
    purchaseHistory: [
      { date: "29 Jan 2026", sku: "EHD-331", product: "Essential Hoodie", channel: "Social", spend: 56 },
      { date: "27 Nov 2025", sku: "PRS-819", product: "Performance Running Shoes", channel: "Email", spend: 63 },
      { date: "15 Oct 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Search", spend: 29 },
      { date: "04 Aug 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Social", spend: 18 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 14,
    engagementScore: 22,
    propensityToChurn: "High",
    nextBestAction: "Win-back campaign — discount-led reactivation via SMS/Social",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "promo-sensitive", "lapsed-45d"],
  },
  {
    id: 3,
    name: "Sofia Andersson",
    email: "sofia.a@email.com",
    city: "London",
    age: 41,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 72100,
    acquisitionChannel: "Direct",
    acquisitionDate: "Jan 2019",
    lastPurchase: "1 week ago",
    purchaseCount: 89,
    avgOrderValue: 81,
    purchaseHistory: [
      { date: "08 Mar 2026", sku: "SCF-203", product: "Merino Scarf & Glove Set", channel: "Direct", spend: 44 },
      { date: "14 Feb 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Direct", spend: 38 },
      { date: "28 Jan 2026", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
      { date: "15 Dec 2025", sku: "UWJ-244", product: "Urban Winter Jacket", channel: "Direct", spend: 85 },
      { date: "03 Nov 2025", sku: "SFT-102", product: "Smart Fitness Tracker", channel: "Direct", spend: 91 },
      { date: "22 Sep 2025", sku: "TPB-551", product: "Travel Pro Backpack", channel: "Email", spend: 86 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 72,
    engagementScore: 97,
    propensityToChurn: "Low",
    nextBestAction: "Invite to brand ambassador programme — NPS 9, refers regularly",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "long-tenure", "referrer"],
  },
  {
    id: 4,
    name: "Johan Eriksson",
    email: "j.eriksson@email.com",
    city: "Birmingham",
    age: 26,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 8900,
    acquisitionChannel: "Google PMAX",
    acquisitionDate: "Nov 2024",
    lastPurchase: "3 weeks ago",
    purchaseCount: 8,
    avgOrderValue: 64,
    purchaseHistory: [
      { date: "22 Feb 2026", sku: "PRS-819", product: "Performance Running Shoes", channel: "Search", spend: 79 },
      { date: "08 Jan 2026", sku: "EHD-331", product: "Essential Hoodie", channel: "Email", spend: 56 },
      { date: "03 Dec 2025", sku: "PRG-445", product: "Pro Running Gloves", channel: "Search", spend: 24 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 31,
    engagementScore: 44,
    propensityToChurn: "Medium",
    nextBestAction: "Nurture into loyalty — recommend next running kit purchase with free shipping offer",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "running-affinity", "new-customer"],
  },
  {
    id: 5,
    name: "Astrid Nilsson",
    email: "astrid.n@email.com",
    city: "Leeds",
    age: 52,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 3200,
    acquisitionChannel: "Facebook Ad",
    acquisitionDate: "Jun 2022",
    lastPurchase: "4 months ago",
    purchaseCount: 6,
    avgOrderValue: 41,
    purchaseHistory: [
      { date: "12 Nov 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 23, returnedOn: "19 Nov 2025" },
      { date: "02 Jul 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Social", spend: 18 },
      { date: "14 Apr 2025", sku: "EHD-331", product: "Essential Hoodie", channel: "Email", spend: 45 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 8,
    engagementScore: 9,
    propensityToChurn: "High",
    nextBestAction: "Final win-back — heavy discount offer before flagging for suppression",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "low-ltv", "high-return-rate", "promo-only"],
  },
  {
    id: 6,
    name: "Lars Johansson",
    email: "l.johansson@email.com",
    city: "Edinburgh",
    age: 47,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 55800,
    acquisitionChannel: "Email Newsletter",
    acquisitionDate: "May 2020",
    lastPurchase: "5 days ago",
    purchaseCount: 62,
    avgOrderValue: 90,
    purchaseHistory: [
      { date: "10 Mar 2026", sku: "WBL-156", product: "Waterproof Base Layer", channel: "Email", spend: 74 },
      { date: "20 Feb 2026", sku: "AWJ-302", product: "Active Windbreaker", channel: "Direct", spend: 65 },
      { date: "05 Jan 2026", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
      { date: "18 Dec 2025", sku: "SCF-203", product: "Merino Scarf & Glove Set", channel: "Direct", spend: 44 },
      { date: "01 Nov 2025", sku: "UWJ-244", product: "Urban Winter Jacket", channel: "Email", spend: 85 },
      { date: "15 Sep 2025", sku: "TPB-551", product: "Travel Pro Backpack", channel: "Direct", spend: 86 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 61,
    engagementScore: 88,
    propensityToChurn: "Low",
    nextBestAction: "Preview spring outerwear drop — respond well to new arrivals emails",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "email-engaged", "outerwear-specialist"],
  },
  {
    id: 7,
    name: "Maja Svensson",
    email: "maja.s@email.com",
    city: "Bristol",
    age: 23,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 14600,
    acquisitionChannel: "TikTok Ad",
    acquisitionDate: "Aug 2024",
    lastPurchase: "10 days ago",
    purchaseCount: 14,
    avgOrderValue: 48,
    purchaseHistory: [
      { date: "05 Mar 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Social", spend: 38 },
      { date: "12 Feb 2026", sku: "TRL-445", product: "Trail Running Leggings", channel: "Social", spend: 62 },
      { date: "22 Jan 2026", sku: "LGG-778", product: "Lightweight Gym Gloves", channel: "Social", spend: 28 },
      { date: "03 Jan 2026", sku: "EHD-331", product: "Essential Hoodie", channel: "Social", spend: 56 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 22,
    engagementScore: 58,
    propensityToChurn: "Low",
    nextBestAction: "Migrate to email channel — engagement score rising, ready for cross-channel nurture",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "social-native", "activewear-affinity", "young-demographic"],
  },
  {
    id: 8,
    name: "Erik Karlsson",
    email: "e.karlsson@email.com",
    city: "Glasgow",
    age: 38,
    segment: "At Risk",
    archetype: "Occasional Buyer",
    ltv: 9800,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Apr 2023",
    lastPurchase: "38 days ago",
    purchaseCount: 11,
    avgOrderValue: 72,
    purchaseHistory: [
      { date: "06 Feb 2026", sku: "PRS-819", product: "Performance Running Shoes", channel: "Search", spend: 79 },
      { date: "29 Oct 2025", sku: "AWJ-302", product: "Active Windbreaker", channel: "Search", spend: 65 },
      { date: "12 Jul 2025", sku: "PRG-445", product: "Pro Running Gloves", channel: "Direct", spend: 24 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 18,
    engagementScore: 28,
    propensityToChurn: "High",
    nextBestAction: "Reactivation — search retargeting with spring running gear creative",
    trend: "down",
    riskScore: "Medium",
    tags: ["at-risk", "running-affinity", "lapsed-38d"],
  },
  // ── NEW PROFILES ─────────────────────────────────────────────────────────────
  {
    id: 9,
    name: "Freya Hansen",
    email: "freya.h@email.com",
    city: "London",
    age: 31,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 61400,
    acquisitionChannel: "Affiliate",
    acquisitionDate: "Feb 2020",
    lastPurchase: "4 days ago",
    purchaseCount: 73,
    avgOrderValue: 84,
    purchaseHistory: [
      { date: "11 Mar 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Direct", spend: 38 },
      { date: "24 Feb 2026", sku: "TRL-445", product: "Trail Running Leggings", channel: "Email", spend: 62 },
      { date: "10 Feb 2026", sku: "SWT-887", product: "Insulated Sports Bottle", channel: "Direct", spend: 22 },
      { date: "19 Jan 2026", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
      { date: "23 Dec 2025", sku: "SCF-203", product: "Merino Scarf & Glove Set", channel: "Direct", spend: 44 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 74,
    engagementScore: 94,
    propensityToChurn: "Low",
    nextBestAction: "Early access to spring activewear drop — yoga/running dual affinity",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "activewear-affinity", "referrer"],
  },
  {
    id: 10,
    name: "Oliver Thompson",
    email: "o.thompson@email.com",
    city: "Manchester",
    age: 27,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 11200,
    acquisitionChannel: "TikTok Ad",
    acquisitionDate: "Jan 2025",
    lastPurchase: "8 days ago",
    purchaseCount: 12,
    avgOrderValue: 55,
    purchaseHistory: [
      { date: "07 Mar 2026", sku: "DSC-091", product: "Dual-Speed Cycling Kit", channel: "Social", spend: 112 },
      { date: "28 Jan 2026", sku: "LGG-778", product: "Lightweight Gym Gloves", channel: "Social", spend: 28 },
      { date: "08 Jan 2026", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 29 },
      { date: "15 Dec 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Social", spend: 18 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 26,
    engagementScore: 52,
    propensityToChurn: "Medium",
    nextBestAction: "Cycling accessories bundle — high intent after Dual-Speed Kit purchase",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "cycling-affinity", "social-native"],
  },
  {
    id: 11,
    name: "Isabella Martinez",
    email: "i.martinez@email.com",
    city: "London",
    age: 44,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 43700,
    acquisitionChannel: "Google PMAX",
    acquisitionDate: "Jul 2021",
    lastPurchase: "6 days ago",
    purchaseCount: 51,
    avgOrderValue: 86,
    purchaseHistory: [
      { date: "09 Mar 2026", sku: "OMB-234", product: "Oxford Messenger Bag", channel: "Email", spend: 95 },
      { date: "18 Feb 2026", sku: "UWJ-244", product: "Urban Winter Jacket", channel: "Direct", spend: 85 },
      { date: "31 Jan 2026", sku: "XTR-509", product: "Extreme Cold Thermal Vest", channel: "Email", spend: 58 },
      { date: "12 Dec 2025", sku: "TPB-551", product: "Travel Pro Backpack", channel: "Direct", spend: 86 },
      { date: "25 Oct 2025", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 59,
    engagementScore: 85,
    propensityToChurn: "Low",
    nextBestAction: "Bags & luggage new arrivals — strong affinity for premium accessories",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "bags-affinity", "email-engaged"],
  },
  {
    id: 12,
    name: "William Clarke",
    email: "w.clarke@email.com",
    city: "Leeds",
    age: 33,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 8100,
    acquisitionChannel: "Meta Ad",
    acquisitionDate: "Nov 2023",
    lastPurchase: "52 days ago",
    purchaseCount: 9,
    avgOrderValue: 41,
    purchaseHistory: [
      { date: "23 Jan 2026", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 23 },
      { date: "29 Nov 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Social", spend: 14 },
      { date: "21 Sep 2025", sku: "EHD-331", product: "Essential Hoodie", channel: "Email", spend: 42 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 11,
    engagementScore: 19,
    propensityToChurn: "High",
    nextBestAction: "Flash sale reactivation — responds to urgency-based discount emails",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "price-sensitive", "lapsed-52d", "promo-only"],
  },
  {
    id: 13,
    name: "Charlotte Wilson",
    email: "c.wilson@email.com",
    city: "Liverpool",
    age: 58,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 2800,
    acquisitionChannel: "Facebook Ad",
    acquisitionDate: "Apr 2022",
    lastPurchase: "5 months ago",
    purchaseCount: 4,
    avgOrderValue: 32,
    purchaseHistory: [
      { date: "15 Oct 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 21 },
      { date: "08 Jun 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Social", spend: 15 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 5,
    engagementScore: 7,
    propensityToChurn: "High",
    nextBestAction: "Suppression candidate — low engagement, high unsubscribe risk after next send",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "suppression-candidate", "low-ltv"],
  },
  {
    id: 14,
    name: "James Anderson",
    email: "j.anderson@email.com",
    city: "Newcastle",
    age: 35,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 9400,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Aug 2024",
    lastPurchase: "19 days ago",
    purchaseCount: 9,
    avgOrderValue: 58,
    purchaseHistory: [
      { date: "25 Feb 2026", sku: "AWJ-302", product: "Active Windbreaker", channel: "Search", spend: 65 },
      { date: "10 Jan 2026", sku: "PRG-445", product: "Pro Running Gloves", channel: "Email", spend: 24 },
      { date: "05 Nov 2025", sku: "EHD-331", product: "Essential Hoodie", channel: "Search", spend: 56 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 28,
    engagementScore: 42,
    propensityToChurn: "Medium",
    nextBestAction: "Loyalty programme enrol — on cusp of Growth→High Value transition",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "outerwear-affinity", "loyalty-candidate"],
  },
  {
    id: 15,
    name: "Emily Wright",
    email: "emily.w@email.com",
    city: "Oxford",
    age: 39,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 38900,
    acquisitionChannel: "Email Newsletter",
    acquisitionDate: "Mar 2021",
    lastPurchase: "3 days ago",
    purchaseCount: 44,
    avgOrderValue: 88,
    purchaseHistory: [
      { date: "12 Mar 2026", sku: "FNP-318", product: "Foldable Neoprene Tote", channel: "Email", spend: 42 },
      { date: "25 Feb 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Direct", spend: 38 },
      { date: "06 Feb 2026", sku: "SFT-102", product: "Smart Fitness Tracker", channel: "Email", spend: 91 },
      { date: "19 Jan 2026", sku: "TRL-445", product: "Trail Running Leggings", channel: "Direct", spend: 62 },
      { date: "04 Dec 2025", sku: "CWL-119", product: "Cashmere Wool Layer", channel: "Email", spend: 89 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 64,
    engagementScore: 87,
    propensityToChurn: "Low",
    nextBestAction: "Spring yoga capsule launch — high affinity for premium activewear",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "activewear-affinity", "email-engaged", "fitness-lifestyle"],
  },
  {
    id: 16,
    name: "Noah Davies",
    email: "n.davies@email.com",
    city: "Cardiff",
    age: 24,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 7200,
    acquisitionChannel: "TikTok Ad",
    acquisitionDate: "Sep 2025",
    lastPurchase: "12 days ago",
    purchaseCount: 7,
    avgOrderValue: 52,
    purchaseHistory: [
      { date: "03 Mar 2026", sku: "LGG-778", product: "Lightweight Gym Gloves", channel: "Social", spend: 28 },
      { date: "14 Feb 2026", sku: "SWT-887", product: "Insulated Sports Bottle", channel: "Social", spend: 22 },
      { date: "28 Jan 2026", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 29 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 19,
    engagementScore: 46,
    propensityToChurn: "Medium",
    nextBestAction: "Accessories cross-sell — recent gym kit purchase signals fitness commitment",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "social-native", "young-demographic", "accessories-affinity"],
  },
  {
    id: 17,
    name: "Zara Ahmed",
    email: "z.ahmed@email.com",
    city: "Birmingham",
    age: 28,
    segment: "At Risk",
    archetype: "Occasional Buyer",
    ltv: 6800,
    acquisitionChannel: "Instagram Ad",
    acquisitionDate: "May 2024",
    lastPurchase: "41 days ago",
    purchaseCount: 6,
    avgOrderValue: 51,
    purchaseHistory: [
      { date: "03 Feb 2026", sku: "TRL-445", product: "Trail Running Leggings", channel: "Social", spend: 62 },
      { date: "01 Dec 2025", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Social", spend: 38 },
      { date: "18 Sep 2025", sku: "LGG-778", product: "Lightweight Gym Gloves", channel: "Email", spend: 28 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 16,
    engagementScore: 24,
    propensityToChurn: "High",
    nextBestAction: "Social retargeting — activewear replenishment creative, focus on Instagram",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "social-native", "activewear-affinity", "lapsed-41d"],
  },
  {
    id: 18,
    name: "Henry Taylor",
    email: "h.taylor@email.com",
    city: "Southampton",
    age: 61,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 4100,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Feb 2021",
    lastPurchase: "6 months ago",
    purchaseCount: 7,
    avgOrderValue: 38,
    purchaseHistory: [
      { date: "10 Sep 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Email", spend: 23 },
      { date: "14 May 2025", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Search", spend: 15 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 6,
    engagementScore: 11,
    propensityToChurn: "High",
    nextBestAction: "Clearance email — single send, suppress if no open within 7 days",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "price-sensitive", "long-inactive"],
  },
  {
    id: 19,
    name: "Amelia Johnson",
    email: "a.johnson@email.com",
    city: "London",
    age: 36,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 52300,
    acquisitionChannel: "Affiliate",
    acquisitionDate: "Jun 2020",
    lastPurchase: "9 days ago",
    purchaseCount: 58,
    avgOrderValue: 90,
    purchaseHistory: [
      { date: "06 Mar 2026", sku: "OMB-234", product: "Oxford Messenger Bag", channel: "Direct", spend: 95 },
      { date: "19 Feb 2026", sku: "FNP-318", product: "Foldable Neoprene Tote", channel: "Email", spend: 42 },
      { date: "08 Feb 2026", sku: "SCF-203", product: "Merino Scarf & Glove Set", channel: "Direct", spend: 44 },
      { date: "20 Jan 2026", sku: "UWJ-244", product: "Urban Winter Jacket", channel: "Email", spend: 85 },
      { date: "05 Dec 2025", sku: "TPB-551", product: "Travel Pro Backpack", channel: "Direct", spend: 86 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 71,
    engagementScore: 93,
    propensityToChurn: "Low",
    nextBestAction: "Exclusive preview of summer bag collection — consistently early adopter",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "bags-affinity", "referrer"],
  },
  {
    id: 20,
    name: "Oscar Brown",
    email: "o.brown@email.com",
    city: "Sheffield",
    age: 22,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 5600,
    acquisitionChannel: "TikTok Ad",
    acquisitionDate: "Nov 2025",
    lastPurchase: "14 days ago",
    purchaseCount: 5,
    avgOrderValue: 44,
    purchaseHistory: [
      { date: "01 Mar 2026", sku: "DSC-091", product: "Dual-Speed Cycling Kit", channel: "Social", spend: 112 },
      { date: "29 Jan 2026", sku: "SWT-887", product: "Insulated Sports Bottle", channel: "Social", spend: 22 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 14,
    engagementScore: 37,
    propensityToChurn: "Medium",
    nextBestAction: "Follow-up cycling accessories — high-value kit purchase signals commitment",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "social-native", "cycling-affinity", "very-new"],
  },
  {
    id: 21,
    name: "Lily Evans",
    email: "lily.e@email.com",
    city: "Cambridge",
    age: 33,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 41200,
    acquisitionChannel: "Google PMAX",
    acquisitionDate: "Oct 2021",
    lastPurchase: "7 days ago",
    purchaseCount: 49,
    avgOrderValue: 84,
    purchaseHistory: [
      { date: "08 Mar 2026", sku: "WBL-156", product: "Waterproof Base Layer", channel: "Email", spend: 74 },
      { date: "22 Feb 2026", sku: "AWJ-302", product: "Active Windbreaker", channel: "Direct", spend: 65 },
      { date: "07 Feb 2026", sku: "TRL-445", product: "Trail Running Leggings", channel: "Email", spend: 62 },
      { date: "14 Jan 2026", sku: "PRS-819", product: "Performance Running Shoes", channel: "Search", spend: 79 },
      { date: "08 Dec 2025", sku: "XTR-509", product: "Extreme Cold Thermal Vest", channel: "Email", spend: 58 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 66,
    engagementScore: 89,
    propensityToChurn: "Low",
    nextBestAction: "Trail running capsule collection — consistent outdoor affinity",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "running-affinity", "outdoor-specialist", "email-engaged"],
  },
  {
    id: 22,
    name: "Lucas Roberts",
    email: "l.roberts@email.com",
    city: "Nottingham",
    age: 31,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 7600,
    acquisitionChannel: "Meta Ad",
    acquisitionDate: "Feb 2024",
    lastPurchase: "48 days ago",
    purchaseCount: 8,
    avgOrderValue: 38,
    purchaseHistory: [
      { date: "27 Jan 2026", sku: "RBS-662", product: "Ribbed Running Socks 3-Pack", channel: "Email", spend: 14 },
      { date: "25 Oct 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Social", spend: 21 },
      { date: "18 Jul 2025", sku: "PRG-445", product: "Pro Running Gloves", channel: "Email", spend: 20 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 12,
    engagementScore: 17,
    propensityToChurn: "High",
    nextBestAction: "Win-back with free shipping threshold — responds to perceived value, not price cuts alone",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "price-sensitive", "lapsed-48d"],
  },
  {
    id: 23,
    name: "Grace Thomas",
    email: "g.thomas@email.com",
    city: "Reading",
    age: 29,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 8800,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Mar 2025",
    lastPurchase: "16 days ago",
    purchaseCount: 8,
    avgOrderValue: 62,
    purchaseHistory: [
      { date: "29 Feb 2026", sku: "YGS-224", product: "Yoga Studio Shorts", channel: "Search", spend: 38 },
      { date: "11 Feb 2026", sku: "SFT-102", product: "Smart Fitness Tracker", channel: "Email", spend: 91 },
      { date: "04 Dec 2025", sku: "LGG-778", product: "Lightweight Gym Gloves", channel: "Search", spend: 28 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 33,
    engagementScore: 50,
    propensityToChurn: "Medium",
    nextBestAction: "Fitness bundle offer — Smart Tracker + accessories cross-sell",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "fitness-lifestyle", "activewear-affinity"],
  },
  {
    id: 24,
    name: "Ethan Robinson",
    email: "e.robinson@email.com",
    city: "Bristol",
    age: 54,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 3600,
    acquisitionChannel: "Google PMAX",
    acquisitionDate: "Jul 2022",
    lastPurchase: "7 months ago",
    purchaseCount: 5,
    avgOrderValue: 35,
    purchaseHistory: [
      { date: "12 Aug 2025", sku: "EHD-331", product: "Essential Hoodie", channel: "Email", spend: 42 },
      { date: "03 Mar 2025", sku: "CTN-421", product: "Classic Cotton Tee", channel: "Search", spend: 23 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 4,
    engagementScore: 8,
    propensityToChurn: "High",
    nextBestAction: "Suppression — no engagement in 7 months, protect deliverability",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "suppression-candidate", "inactive-7m"],
  },
];

// ── Segment summary helper ────────────────────────────────────────────────────

export function getSegmentSummary() {
  const counts = CUSTOMERS.reduce<Record<string, number>>((acc, c) => {
    acc[c.segment] = (acc[c.segment] ?? 0) + 1;
    return acc;
  }, {});

  const avgLTV = CUSTOMERS.reduce<Record<string, { total: number; count: number }>>((acc, c) => {
    if (!acc[c.segment]) acc[c.segment] = { total: 0, count: 0 };
    acc[c.segment].total += c.ltv;
    acc[c.segment].count += 1;
    return acc;
  }, {});

  return Object.entries(counts).map(([segment, count]) => ({
    segment,
    count,
    avgLTV: Math.round(avgLTV[segment].total / avgLTV[segment].count),
    totalLTV: avgLTV[segment].total,
  }));
}
