/**
 * Extended Customer Dataset — Winter Weather Hazard Simulation
 *
 * 24 complete customer profiles with purchase histories, channel attribution,
 * lifecycle stages, propensity scores, and journey context.
 *
 * Consistent with segments and archetypes shown in app/customers/page.tsx.
 * SKU naming: [3-letter category]-[3-digit number]
 */

export type CustomerSegment = "High Value" | "Growth" | "At Risk" | "Dormant";
export type CustomerArchetype =
  | "Loyal Buyer"
  | "Brand Advocate"
  | "Deal Hunter"
  | "Trend Follower"
  | "Occasional Buyer"
  | "Bargain Seeker";
export type ChurnRisk = "Low" | "Medium" | "High";
export type TrendDirection = "up" | "down" | "flat";

export interface PurchaseEvent {
  date: string;          // e.g. "12 Mar 2026"
  sku: string;
  product: string;
  channel: "Email" | "Direct" | "Search" | "Social" | "Affiliate";
  spend: number;         // $
  returnedOn?: string;   // date if returned
}

export interface CustomerProfile {
  id: number;
  name: string;
  email: string;
  city: string;
  age: number;
  segment: CustomerSegment;
  archetype: CustomerArchetype;
  ltv: number;                   // lifetime value $
  acquisitionChannel: string;
  acquisitionDate: string;       // "Jan 2024"
  lastPurchase: string;          // relative "3 days ago"
  purchaseCount: number;
  avgOrderValue: number;         // $
  purchaseHistory: PurchaseEvent[];
  preferredChannel: string;
  emailOpenRate: number;         // %
  engagementScore: number;       // 0-100
  propensityToChurn: ChurnRisk;
  nextBestAction: string;
  trend: TrendDirection;
  riskScore: ChurnRisk;
  tags: string[];
}

// ── Storm-critical product catalogue (SKUs used across purchase histories) ──

export const PRODUCT_CATALOGUE: Record<string, { name: string; category: string; price: number }> = {
  "WTR-101": { name: "Water Bulk Pack (24ct)", category: "Water & Emergency Supplies", price: 12 },
  "WTR-102": { name: "Water Filtration Jug", category: "Water & Emergency Supplies", price: 34 },
  "BAT-201": { name: "AA Batteries 48-Pack", category: "Batteries & Lighting", price: 24 },
  "BAT-202": { name: "LED Flashlight Pro", category: "Batteries & Lighting", price: 42 },
  "BAT-203": { name: "Portable Lantern", category: "Batteries & Lighting", price: 38 },
  "FAK-301": { name: "First Aid Kit Deluxe", category: "First Aid & Medical", price: 56 },
  "FAK-302": { name: "Prescription Replenishment Pack", category: "First Aid & Medical", price: 28 },
  "RDY-401": { name: "Chilled Ready Meals (6-pack)", category: "Ready Meals & Shelf-Stable Food", price: 18 },
  "RDY-402": { name: "Shelf-Stable Soup Variety (12ct)", category: "Ready Meals & Shelf-Stable Food", price: 22 },
  "RDY-403": { name: "Emergency Protein Bars (24ct)", category: "Ready Meals & Shelf-Stable Food", price: 28 },
  "FRZ-501": { name: "Frozen Desserts Variety Pack", category: "Frozen Foods", price: 16 },
  "FRZ-502": { name: "Frozen Pizza Bundle (4ct)", category: "Frozen Foods", price: 24 },
  "PET-601": { name: "Emergency Pet Food (Dog, 20lb)", category: "Pet Supplies", price: 38 },
  "PET-602": { name: "Emergency Pet Food (Cat, 15lb)", category: "Pet Supplies", price: 32 },
  "WRM-701": { name: "Insulated Winter Coat", category: "Warm Clothing & Blankets", price: 89 },
  "WRM-702": { name: "Thermal Blanket Bundle (3ct)", category: "Warm Clothing & Blankets", price: 54 },
  "WRM-703": { name: "Fleece-Lined Gloves", category: "Warm Clothing & Blankets", price: 22 },
  "EMG-801": { name: "Portable Phone Charger", category: "Water & Emergency Supplies", price: 36 },
  "EMG-802": { name: "Emergency Radio (Hand-Crank)", category: "Water & Emergency Supplies", price: 48 },
  "SAL-901": { name: "Mixed-Leaf Salad (Family)", category: "Ready Meals & Shelf-Stable Food", price: 8 },
};

// ── 24 customer profiles ─────────────────────────────────────────────────────

export const CUSTOMERS: CustomerProfile[] = [
  // ── HIGH VALUE — Storm Prep Buyers ──────────────────────────────────────
  {
    id: 1,
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    city: "Boston",
    age: 34,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 4820,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Sep 2021",
    lastPurchase: "2 days ago",
    purchaseCount: 47,
    avgOrderValue: 68,
    purchaseHistory: [
      { date: "13 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Email", spend: 48 },
      { date: "13 Mar 2026", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Email", spend: 24 },
      { date: "12 Mar 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Direct", spend: 56 },
      { date: "11 Mar 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Direct", spend: 54 },
      { date: "04 Mar 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Email", spend: 89 },
      { date: "18 Feb 2026", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Direct", spend: 22 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 68,
    engagementScore: 91,
    propensityToChurn: "Low",
    nextBestAction: "Expedite subscription delivery before storm lockdown — high affinity for essentials",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "email-engaged", "storm-prep-buyer", "subscription-active"],
  },
  {
    id: 2,
    name: "Marcus Chen",
    email: "m.chen@email.com",
    city: "Newark",
    age: 29,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 1240,
    acquisitionChannel: "App Push Notification",
    acquisitionDate: "Mar 2023",
    lastPurchase: "45 days ago",
    purchaseCount: 18,
    avgOrderValue: 42,
    purchaseHistory: [
      { date: "29 Jan 2026", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Social", spend: 28 },
      { date: "27 Nov 2025", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Email", spend: 22 },
      { date: "15 Oct 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Search", spend: 22 },
      { date: "04 Aug 2025", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 24 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 14,
    engagementScore: 22,
    propensityToChurn: "High",
    nextBestAction: "Storm alert reactivation — push notification with emergency essentials bundle",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "promo-sensitive", "lapsed-45d"],
  },
  {
    id: 3,
    name: "Jessica Rodriguez",
    email: "jessica.r@email.com",
    city: "New York",
    age: 41,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 7210,
    acquisitionChannel: "Direct",
    acquisitionDate: "Jan 2019",
    lastPurchase: "1 week ago",
    purchaseCount: 89,
    avgOrderValue: 52,
    purchaseHistory: [
      { date: "08 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Direct", spend: 96 },
      { date: "08 Mar 2026", sku: "BAT-202", product: "LED Flashlight Pro", channel: "Direct", spend: 42 },
      { date: "07 Mar 2026", sku: "EMG-802", product: "Emergency Radio (Hand-Crank)", channel: "Email", spend: 48 },
      { date: "28 Jan 2026", sku: "WRM-702", product: "Thermal Blanket Bundle (3ct)", channel: "Direct", spend: 54 },
      { date: "15 Dec 2025", sku: "PET-601", product: "Emergency Pet Food (Dog, 20lb)", channel: "Direct", spend: 38 },
      { date: "03 Nov 2025", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Email", spend: 56 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 72,
    engagementScore: 97,
    propensityToChurn: "Low",
    nextBestAction: "Invite to storm-prep loyalty rewards — NPS 9, refers regularly",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "long-tenure", "referrer", "pet-owner"],
  },
  {
    id: 4,
    name: "Tyler Washington",
    email: "t.washington@email.com",
    city: "Philadelphia",
    age: 26,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 890,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Nov 2024",
    lastPurchase: "3 weeks ago",
    purchaseCount: 8,
    avgOrderValue: 44,
    purchaseHistory: [
      { date: "22 Feb 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Search", spend: 89 },
      { date: "08 Jan 2026", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Email", spend: 28 },
      { date: "03 Dec 2025", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Search", spend: 22 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 31,
    engagementScore: 44,
    propensityToChurn: "Medium",
    nextBestAction: "Storm essentials bundle — warm clothing + emergency supplies cross-sell",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "warm-clothing-affinity", "new-customer"],
  },
  {
    id: 5,
    name: "Patricia Novak",
    email: "p.novak@email.com",
    city: "Hartford",
    age: 52,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 320,
    acquisitionChannel: "Email Campaign",
    acquisitionDate: "Jun 2022",
    lastPurchase: "4 months ago",
    purchaseCount: 6,
    avgOrderValue: 26,
    purchaseHistory: [
      { date: "12 Nov 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Email", spend: 22 },
      { date: "02 Jul 2025", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 24 },
      { date: "14 Apr 2025", sku: "SAL-901", product: "Mixed-Leaf Salad (Family)", channel: "Email", spend: 8 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 8,
    engagementScore: 9,
    propensityToChurn: "High",
    nextBestAction: "Emergency storm alert — final reactivation attempt before suppression",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "low-ltv", "promo-only"],
  },
  {
    id: 6,
    name: "David Kowalski",
    email: "d.kowalski@email.com",
    city: "Albany",
    age: 47,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 5580,
    acquisitionChannel: "Email Newsletter",
    acquisitionDate: "May 2020",
    lastPurchase: "5 days ago",
    purchaseCount: 62,
    avgOrderValue: 58,
    purchaseHistory: [
      { date: "10 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Email", spend: 72 },
      { date: "10 Mar 2026", sku: "EMG-801", product: "Portable Phone Charger", channel: "Direct", spend: 36 },
      { date: "09 Mar 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Email", spend: 56 },
      { date: "05 Jan 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Email", spend: 89 },
      { date: "18 Dec 2025", sku: "WRM-702", product: "Thermal Blanket Bundle (3ct)", channel: "Direct", spend: 54 },
      { date: "01 Nov 2025", sku: "PET-602", product: "Emergency Pet Food (Cat, 15lb)", channel: "Email", spend: 32 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 61,
    engagementScore: 88,
    propensityToChurn: "Low",
    nextBestAction: "Expedite subscription — respond well to emergency prep emails",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "email-engaged", "emergency-prep-buyer", "pet-owner"],
  },
  {
    id: 7,
    name: "Mia Thompson",
    email: "mia.t@email.com",
    city: "Providence",
    age: 23,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 1460,
    acquisitionChannel: "App Push Notification",
    acquisitionDate: "Aug 2024",
    lastPurchase: "10 days ago",
    purchaseCount: 14,
    avgOrderValue: 36,
    purchaseHistory: [
      { date: "05 Mar 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Social", spend: 36 },
      { date: "12 Feb 2026", sku: "FRZ-501", product: "Frozen Desserts Variety Pack", channel: "Social", spend: 16 },
      { date: "22 Jan 2026", sku: "SAL-901", product: "Mixed-Leaf Salad (Family)", channel: "Social", spend: 16 },
      { date: "03 Jan 2026", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Social", spend: 28 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 22,
    engagementScore: 58,
    propensityToChurn: "Low",
    nextBestAction: "App-based storm prep checklist — engagement rising, ready for cross-channel",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "app-native", "food-affinity", "young-demographic"],
  },
  {
    id: 8,
    name: "Robert Kim",
    email: "r.kim@email.com",
    city: "Pittsburgh",
    age: 38,
    segment: "At Risk",
    archetype: "Occasional Buyer",
    ltv: 980,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Apr 2023",
    lastPurchase: "38 days ago",
    purchaseCount: 11,
    avgOrderValue: 48,
    purchaseHistory: [
      { date: "06 Feb 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Search", spend: 89 },
      { date: "29 Oct 2025", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Search", spend: 22 },
      { date: "12 Jul 2025", sku: "BAT-202", product: "LED Flashlight Pro", channel: "Direct", spend: 42 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 18,
    engagementScore: 28,
    propensityToChurn: "High",
    nextBestAction: "Storm alert reactivation — search retargeting with emergency bundle",
    trend: "down",
    riskScore: "Medium",
    tags: ["at-risk", "warm-clothing-affinity", "lapsed-38d"],
  },
  // ── ADDITIONAL PROFILES ──────────────────────────────────────────────────
  {
    id: 9,
    name: "Amanda Foster",
    email: "amanda.f@email.com",
    city: "New York",
    age: 31,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 6140,
    acquisitionChannel: "Affiliate",
    acquisitionDate: "Feb 2020",
    lastPurchase: "4 days ago",
    purchaseCount: 73,
    avgOrderValue: 54,
    purchaseHistory: [
      { date: "11 Mar 2026", sku: "PET-601", product: "Emergency Pet Food (Dog, 20lb)", channel: "Direct", spend: 76 },
      { date: "11 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Direct", spend: 36 },
      { date: "24 Feb 2026", sku: "FAK-302", product: "Prescription Replenishment Pack", channel: "Email", spend: 28 },
      { date: "10 Feb 2026", sku: "EMG-801", product: "Portable Phone Charger", channel: "Direct", spend: 36 },
      { date: "19 Jan 2026", sku: "WRM-702", product: "Thermal Blanket Bundle (3ct)", channel: "Email", spend: 54 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 74,
    engagementScore: 94,
    propensityToChurn: "Low",
    nextBestAction: "Pet owner storm bundle — dog food + blankets + water",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "pet-owner", "referrer", "subscription-active"],
  },
  {
    id: 10,
    name: "Brian O'Sullivan",
    email: "b.osullivan@email.com",
    city: "Newark",
    age: 27,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 1120,
    acquisitionChannel: "App Push Notification",
    acquisitionDate: "Jan 2025",
    lastPurchase: "8 days ago",
    purchaseCount: 12,
    avgOrderValue: 38,
    purchaseHistory: [
      { date: "07 Mar 2026", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 48 },
      { date: "07 Mar 2026", sku: "BAT-202", product: "LED Flashlight Pro", channel: "Social", spend: 42 },
      { date: "28 Jan 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Social", spend: 18 },
      { date: "08 Jan 2026", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Email", spend: 22 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 26,
    engagementScore: 52,
    propensityToChurn: "Medium",
    nextBestAction: "Emergency lighting bundle — battery + flashlight cross-sell completed, suggest lantern",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "batteries-affinity", "app-native"],
  },
  {
    id: 11,
    name: "Rachel Martinez",
    email: "r.martinez@email.com",
    city: "Boston",
    age: 44,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 4370,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Jul 2021",
    lastPurchase: "6 days ago",
    purchaseCount: 51,
    avgOrderValue: 56,
    purchaseHistory: [
      { date: "09 Mar 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Email", spend: 56 },
      { date: "09 Mar 2026", sku: "FAK-302", product: "Prescription Replenishment Pack", channel: "Email", spend: 28 },
      { date: "18 Feb 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Direct", spend: 48 },
      { date: "31 Jan 2026", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Email", spend: 22 },
      { date: "12 Dec 2025", sku: "EMG-802", product: "Emergency Radio (Hand-Crank)", channel: "Direct", spend: 48 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 59,
    engagementScore: 85,
    propensityToChurn: "Low",
    nextBestAction: "Medical preparedness bundle — first aid + prescription replenishment cross-sell",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "medical-affinity", "email-engaged"],
  },
  {
    id: 12,
    name: "Kevin Murphy",
    email: "k.murphy@email.com",
    city: "Hartford",
    age: 33,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 810,
    acquisitionChannel: "SMS Alert",
    acquisitionDate: "Nov 2023",
    lastPurchase: "52 days ago",
    purchaseCount: 9,
    avgOrderValue: 32,
    purchaseHistory: [
      { date: "23 Jan 2026", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Email", spend: 22 },
      { date: "29 Nov 2025", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 24 },
      { date: "21 Sep 2025", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Email", spend: 28 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 11,
    engagementScore: 19,
    propensityToChurn: "High",
    nextBestAction: "Storm urgency reactivation — emergency essentials discount push",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "price-sensitive", "lapsed-52d", "promo-only"],
  },
  {
    id: 13,
    name: "Dorothy Williams",
    email: "d.williams@email.com",
    city: "Syracuse",
    age: 58,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 280,
    acquisitionChannel: "Email Campaign",
    acquisitionDate: "Apr 2022",
    lastPurchase: "5 months ago",
    purchaseCount: 4,
    avgOrderValue: 24,
    purchaseHistory: [
      { date: "15 Oct 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Email", spend: 22 },
      { date: "08 Jun 2025", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 24 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 5,
    engagementScore: 7,
    propensityToChurn: "High",
    nextBestAction: "Suppression candidate — low engagement, high unsubscribe risk",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "suppression-candidate", "low-ltv"],
  },
  {
    id: 14,
    name: "James Anderson",
    email: "j.anderson@email.com",
    city: "Burlington",
    age: 35,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 940,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Aug 2024",
    lastPurchase: "19 days ago",
    purchaseCount: 9,
    avgOrderValue: 46,
    purchaseHistory: [
      { date: "25 Feb 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Search", spend: 89 },
      { date: "10 Jan 2026", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Email", spend: 22 },
      { date: "05 Nov 2025", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Search", spend: 28 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 28,
    engagementScore: 42,
    propensityToChurn: "Medium",
    nextBestAction: "Storm preparedness bundle — on cusp of Growth→High Value transition",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "warm-clothing-affinity", "loyalty-candidate"],
  },
  {
    id: 15,
    name: "Emily Wright",
    email: "emily.w@email.com",
    city: "Stamford",
    age: 39,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 3890,
    acquisitionChannel: "Email Newsletter",
    acquisitionDate: "Mar 2021",
    lastPurchase: "3 days ago",
    purchaseCount: 44,
    avgOrderValue: 62,
    purchaseHistory: [
      { date: "12 Mar 2026", sku: "PET-602", product: "Emergency Pet Food (Cat, 15lb)", channel: "Email", spend: 64 },
      { date: "12 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Email", spend: 48 },
      { date: "25 Feb 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Direct", spend: 36 },
      { date: "06 Feb 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Email", spend: 56 },
      { date: "19 Jan 2026", sku: "WRM-702", product: "Thermal Blanket Bundle (3ct)", channel: "Direct", spend: 54 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 64,
    engagementScore: 87,
    propensityToChurn: "Low",
    nextBestAction: "Pet owner storm bundle — cat food + essentials cross-sell",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "pet-owner", "email-engaged", "subscription-active"],
  },
  {
    id: 16,
    name: "Noah Patel",
    email: "n.patel@email.com",
    city: "White Plains",
    age: 24,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 720,
    acquisitionChannel: "App Push Notification",
    acquisitionDate: "Sep 2025",
    lastPurchase: "12 days ago",
    purchaseCount: 7,
    avgOrderValue: 38,
    purchaseHistory: [
      { date: "03 Mar 2026", sku: "BAT-203", product: "Portable Lantern", channel: "Social", spend: 38 },
      { date: "14 Feb 2026", sku: "EMG-801", product: "Portable Phone Charger", channel: "Social", spend: 36 },
      { date: "28 Jan 2026", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Email", spend: 28 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 19,
    engagementScore: 46,
    propensityToChurn: "Medium",
    nextBestAction: "Emergency tech bundle — charger + lantern + radio cross-sell",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "app-native", "young-demographic", "tech-affinity"],
  },
  {
    id: 17,
    name: "Zara Ahmed",
    email: "z.ahmed@email.com",
    city: "Philadelphia",
    age: 28,
    segment: "At Risk",
    archetype: "Occasional Buyer",
    ltv: 680,
    acquisitionChannel: "SMS Alert",
    acquisitionDate: "May 2024",
    lastPurchase: "41 days ago",
    purchaseCount: 6,
    avgOrderValue: 34,
    purchaseHistory: [
      { date: "03 Feb 2026", sku: "FRZ-501", product: "Frozen Desserts Variety Pack", channel: "Social", spend: 16 },
      { date: "01 Dec 2025", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Social", spend: 18 },
      { date: "18 Sep 2025", sku: "SAL-901", product: "Mixed-Leaf Salad (Family)", channel: "Email", spend: 8 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 16,
    engagementScore: 24,
    propensityToChurn: "High",
    nextBestAction: "SMS storm alert — frozen/chilled food replenishment before cold-chain disruption",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "app-native", "food-affinity", "lapsed-41d"],
  },
  {
    id: 18,
    name: "Henry Taylor",
    email: "h.taylor@email.com",
    city: "Trenton",
    age: 61,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 410,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Feb 2021",
    lastPurchase: "6 months ago",
    purchaseCount: 7,
    avgOrderValue: 28,
    purchaseHistory: [
      { date: "10 Sep 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Email", spend: 22 },
      { date: "14 May 2025", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Search", spend: 24 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 6,
    engagementScore: 11,
    propensityToChurn: "High",
    nextBestAction: "Emergency alert email — single send, suppress if no open within 7 days",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "price-sensitive", "long-inactive"],
  },
  {
    id: 19,
    name: "Amelia Johnson",
    email: "a.johnson@email.com",
    city: "New York",
    age: 36,
    segment: "High Value",
    archetype: "Brand Advocate",
    ltv: 5230,
    acquisitionChannel: "Affiliate",
    acquisitionDate: "Jun 2020",
    lastPurchase: "9 days ago",
    purchaseCount: 58,
    avgOrderValue: 58,
    purchaseHistory: [
      { date: "06 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Direct", spend: 72 },
      { date: "06 Mar 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Direct", spend: 56 },
      { date: "19 Feb 2026", sku: "EMG-802", product: "Emergency Radio (Hand-Crank)", channel: "Email", spend: 48 },
      { date: "08 Feb 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Direct", spend: 89 },
      { date: "20 Jan 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Email", spend: 36 },
    ],
    preferredChannel: "Direct",
    emailOpenRate: 71,
    engagementScore: 93,
    propensityToChurn: "Low",
    nextBestAction: "Complete storm prep kit — water + first aid done, add batteries + radio",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "brand-advocate", "emergency-prep-buyer", "referrer"],
  },
  {
    id: 20,
    name: "Oscar Brown",
    email: "o.brown@email.com",
    city: "Bridgeport",
    age: 22,
    segment: "Growth",
    archetype: "Trend Follower",
    ltv: 560,
    acquisitionChannel: "App Push Notification",
    acquisitionDate: "Nov 2025",
    lastPurchase: "14 days ago",
    purchaseCount: 5,
    avgOrderValue: 34,
    purchaseHistory: [
      { date: "01 Mar 2026", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Social", spend: 48 },
      { date: "29 Jan 2026", sku: "EMG-801", product: "Portable Phone Charger", channel: "Social", spend: 36 },
    ],
    preferredChannel: "Social",
    emailOpenRate: 14,
    engagementScore: 37,
    propensityToChurn: "Medium",
    nextBestAction: "Emergency power bundle — charger + batteries purchased, suggest lantern + radio",
    trend: "up",
    riskScore: "Low",
    tags: ["growth", "app-native", "tech-affinity", "very-new"],
  },
  {
    id: 21,
    name: "Lily Evans",
    email: "lily.e@email.com",
    city: "Cambridge",
    age: 33,
    segment: "High Value",
    archetype: "Loyal Buyer",
    ltv: 4120,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Oct 2021",
    lastPurchase: "7 days ago",
    purchaseCount: 49,
    avgOrderValue: 52,
    purchaseHistory: [
      { date: "08 Mar 2026", sku: "WTR-102", product: "Water Filtration Jug", channel: "Email", spend: 34 },
      { date: "08 Mar 2026", sku: "WTR-101", product: "Water Bulk Pack (24ct)", channel: "Email", spend: 48 },
      { date: "22 Feb 2026", sku: "RDY-401", product: "Chilled Ready Meals (6-pack)", channel: "Direct", spend: 54 },
      { date: "07 Feb 2026", sku: "FRZ-502", product: "Frozen Pizza Bundle (4ct)", channel: "Email", spend: 24 },
      { date: "14 Jan 2026", sku: "WRM-701", product: "Insulated Winter Coat", channel: "Search", spend: 89 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 66,
    engagementScore: 89,
    propensityToChurn: "Low",
    nextBestAction: "Subscription expedite — water + ready meals subscription before lockdown",
    trend: "up",
    riskScore: "Low",
    tags: ["vip", "water-affinity", "subscription-active", "email-engaged"],
  },
  {
    id: 22,
    name: "Lucas Roberts",
    email: "l.roberts@email.com",
    city: "Paterson",
    age: 31,
    segment: "At Risk",
    archetype: "Deal Hunter",
    ltv: 760,
    acquisitionChannel: "SMS Alert",
    acquisitionDate: "Feb 2024",
    lastPurchase: "48 days ago",
    purchaseCount: 8,
    avgOrderValue: 28,
    purchaseHistory: [
      { date: "27 Jan 2026", sku: "BAT-201", product: "AA Batteries 48-Pack", channel: "Email", spend: 24 },
      { date: "25 Oct 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Social", spend: 22 },
      { date: "18 Jul 2025", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Email", spend: 22 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 12,
    engagementScore: 17,
    propensityToChurn: "High",
    nextBestAction: "Storm urgency win-back — free shipping on emergency essentials bundle",
    trend: "down",
    riskScore: "High",
    tags: ["at-risk", "price-sensitive", "lapsed-48d"],
  },
  {
    id: 23,
    name: "Grace Thomas",
    email: "g.thomas@email.com",
    city: "Springfield",
    age: 29,
    segment: "Growth",
    archetype: "Occasional Buyer",
    ltv: 880,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Mar 2025",
    lastPurchase: "16 days ago",
    purchaseCount: 8,
    avgOrderValue: 42,
    purchaseHistory: [
      { date: "28 Feb 2026", sku: "PET-601", product: "Emergency Pet Food (Dog, 20lb)", channel: "Search", spend: 38 },
      { date: "11 Feb 2026", sku: "FAK-301", product: "First Aid Kit Deluxe", channel: "Email", spend: 56 },
      { date: "04 Dec 2025", sku: "WRM-703", product: "Fleece-Lined Gloves", channel: "Search", spend: 22 },
    ],
    preferredChannel: "Search",
    emailOpenRate: 33,
    engagementScore: 50,
    propensityToChurn: "Medium",
    nextBestAction: "Pet storm bundle — dog food + water + blanket cross-sell",
    trend: "up",
    riskScore: "Medium",
    tags: ["growth", "pet-owner", "medical-affinity"],
  },
  {
    id: 24,
    name: "Ethan Robinson",
    email: "e.robinson@email.com",
    city: "Scranton",
    age: 54,
    segment: "Dormant",
    archetype: "Bargain Seeker",
    ltv: 360,
    acquisitionChannel: "Google Search",
    acquisitionDate: "Jul 2022",
    lastPurchase: "7 months ago",
    purchaseCount: 5,
    avgOrderValue: 26,
    purchaseHistory: [
      { date: "12 Aug 2025", sku: "RDY-403", product: "Emergency Protein Bars (24ct)", channel: "Email", spend: 28 },
      { date: "03 Mar 2025", sku: "RDY-402", product: "Shelf-Stable Soup Variety (12ct)", channel: "Search", spend: 22 },
    ],
    preferredChannel: "Email",
    emailOpenRate: 4,
    engagementScore: 8,
    propensityToChurn: "High",
    nextBestAction: "Suppression — no engagement in 7 months, protect deliverability",
    trend: "down",
    riskScore: "High",
    tags: ["dormant", "suppression-candidate", "inactive-7m"],
  },
];

// ── Segment summary helper ────────────────────────────────────────────────────

export function getSegmentSummary() {
  const counts = CUSTOMERS.reduce<Record<string, number>>((acc, c) => {
    acc[c.segment] = (acc[c.segment] ?? 0) + 1;
    return acc;
  }, {});

  const avgLTV = CUSTOMERS.reduce<Record<string, { total: number; count: number }>>((acc, c) => {
    if (!acc[c.segment]) acc[c.segment] = { total: 0, count: 0 };
    acc[c.segment].total += c.ltv;
    acc[c.segment].count += 1;
    return acc;
  }, {});

  return Object.entries(counts).map(([segment, count]) => ({
    segment,
    count,
    avgLTV: Math.round(avgLTV[segment].total / avgLTV[segment].count),
    totalLTV: avgLTV[segment].total,
  }));
}
